name: Publish to NPM

on:
  
  workflow_dispatch:

  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup Node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14.x'
      #     registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies and build 🔧
        run: npm install

      - name: Publish package on NPM 📦
        run: |
          echo _auth=$NPM_TOKEN >> .npmrc
          echo email=$NPM_EMAIL >> .npmrc
          echo always-auth=true >> .npmrc
          cat .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package on Github 📦
        run: |
          node scripts/changeNpmRegistry --registry=https://npm.pkg.github.com --name=@w3dev/ethereum-lists
          npm publish --@w3dev:registry=https://npm.pkg.github.com


